# Generated by Django 5.2.5 on 2025-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('mother', models.CharField(max_length=20)),
                ('video', models.CharField(max_length=20)),
            ],
        ),
    ]
