# Generated by Django 5.2.5 on 2025-09-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='equipos'),
        ),
    ]
