# Generated by Django 5.2.5 on 2025-09-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='gabinete',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
